Feature/createreadme
CC-positive/ThreeGoodThings-API pull request #22
Opened 2020-11-20 14:51 UTC by TomoyaHirano

readmeを作成しました。またSwaggerでAPI仕様を作成しました。

2020-11-20 15:07 UTC, h-tsuboi918 requested changes
数点質問とRequest changesを付けましたので確認をお願いします。

2020-11-20 15:07 UTC, h-tsuboi918 commented on docs/dist/index.html
> +    <style>
cssは別出しできないですか？

2020-11-20 15:07 UTC, h-tsuboi918 commented on docs/dist/index.html
> +<html lang="en">
lang="ja"ではないですか？

2020-11-20 15:07 UTC, h-tsuboi918 commented on docs/dist/index.html
> +    <title>Swagger UI</title>
TGT API Documentationとかに変えたほうがいい気がします。

2020-11-20 15:07 UTC, h-tsuboi918 commented on docs/apispec.yaml
> +  description: This is the specification of ThreeGoodThings-API. See https://github.com/CC-positive/ThreeGoodThings-API
URL部分は
`[https://github.com/CC-positive/ThreeGoodThings-API](https://github.com/CC-positive/ThreeGoodThings-API)`
のほうが良いかと。

2020-11-20 15:07 UTC, h-tsuboi918 commented on docs/dist/oauth2-redirect.html
> +<!doctype html>
これって何用のファイルですか？

2020-11-24 00:27 UTC, TomoyaHirano commented
@h-tsuboi918 
html, js, css部分に指摘いただきすみません。。。
以下のqiita記事に沿ってSwaggerUIのgithubリポジトリのdistディレクトリを流用した形で、yamlファイル以外は全く修正していませんでした。
https://qiita.com/godgarden/items/be420a8c165f4a0f3ad8

修正案として以下３つくらいあると思います。どれが良さそうか相談させてください。

- yaml以外は修正しない
- ユーザから実際に見える箇所は修正する、見えない箇所は修正しない
- ユーザから見えない箇所も含め最適化する

2020-11-24 01:43 UTC, TomoyaHirano commented on docs/dist/index.html
> +    <style>
別途会話させていただいたとおり、修正しないことにしました（SwaggerUI部分なので深入りしない）

2020-11-24 01:44 UTC, TomoyaHirano commented on docs/dist/index.html
> +<html lang="en">
別途会話させていただいたとおり、修正しないことにしました（SwaggerUI部分なので深入りしない）

2020-11-24 01:44 UTC, TomoyaHirano commented on docs/dist/index.html
> +    <title>Swagger UI</title>
修正しました。

2020-11-24 01:44 UTC, TomoyaHirano commented on docs/apispec.yaml
> +  description: This is the specification of ThreeGoodThings-API. See https://github.com/CC-positive/ThreeGoodThings-API
修正しました。

2020-11-24 01:44 UTC, TomoyaHirano commented on docs/dist/oauth2-redirect.html
> +<!doctype html>
別途会話させていただいたとおり、修正しないことにしました（SwaggerUI部分なので深入りしない）

2020-11-24 01:44 UTC, TomoyaHirano commented
@h-tsuboi918 
レビュー指摘対応しました、確認をお願いします。

2020-11-24 01:48 UTC, h-tsuboi918 approved these changes
LGTM :+1:
[![LGTM](https://media2.giphy.com/media/cncGAb1uEpgWlWQdwK/200_d.gif)](https://giphy.com/gifs/thumbs-up-alpha-rooster-cncGAb1uEpgWlWQdwK)
Powered By GIPHY. Powered By [LGTM reloaded](https://chrome.google.com/webstore/detail/lgtm-reloaded/hefidgcceobmmaiekccmbjpdcmbjklej).

2020-11-24 01:48 UTC, merged